name: develop ci/cd pipeline
on:
  push:
    branches:
      - github-action
jobs:
  build:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: Gov.News.WebApp
    environment: 'DEV'
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup .NET Core
        uses: actions/setup-dotnet@v2
        with:
          dotnet-version: 5.x

      - name: Build .NET Core App
        run: |
          dotnet restore
          dotnet build

      - name: Install oc
        uses: redhat-actions/openshift-tools-installer@v1
        with:
          oc: 4.10

      - name: Log in to OpenShift
        uses: redhat-actions/oc-login@v1
        with:
          openshift_server_url: ${{ secrets.OPENSHIFT_SERVER_URL }}
          openshift_token: ${{ secrets.OPENSHIFT_LOGIN_TOKEN }}
          insecure_skip_tls_verify: true
          namespace: ${{ secrets.OPENSHIFT_NAMESPACE }}

      #- name: Start OpenShift Build
        #run: |
          #oc start-build bc/hub-api-develop-docker --wait
      
      - name: Trigger Opneshift Pipeline
        run: |
          oc project ${{ secrets.OPENSHIFT_NAMESPACE }}
          tkn pipeline start news-webapp-develop-pipeline 
            --showlog